### ISSUE TITLE
Missing translation exposed during email confirmation

### ISSUE THREAD

**Issue by Cruikshanks** [DEFRA/ruby-services-team#12]
ITSM call 1622959 highlighted a missing translation. From what we can gather a back office user updates the email address against a registration, and this sends an email to the user to confirm the email address.

When the user clicks the link they see the following error.

![screenshot](https://user-images.githubusercontent.com/1789650/30053122-a3b69962-921f-11e7-89fa-bffa3ea5022d.jpg)

In this particular case because they were trying to update multiple registrations, the user was getting multiple emails and that seemed to prevent the change from taking place, though more investigation would be needed.

In the meantime we need to add the missing translation, only problem is we don't actually understand what is wrong with the password, so don't know what error message to provide.

Translation missing from [en.yml](https://github.com/DEFRA/waste-carriers-frontend/blob/develop/config/locales/en.yml#L266)

Identified the rest of the content comes from [devise.en.yml](https://github.com/DEFRA/waste-carriers-frontend/blob/develop/config/locales/devise.en.yml)

The view is [app/views/devise/confirmations/new.html.erb](https://github.com/DEFRA/waste-carriers-frontend/blob/develop/app/views/devise/confirmations/new.html.erb)

The method that expects there to be a `en.errors.messages.password` translation is [devise_token_error_messages!](https://github.com/DEFRA/waste-carriers-frontend/blob/develop/app/helpers/devise_helper.rb#L22)

**Comment by Cruikshanks** [comment]
It is our intention to migrate the remaining functionality in the frontend into our new apps.

Hence have moved this across in the spirit of having a single list of issues, but it is not our intention to fix it because of this.

**Comment by irisfaraway** [comment]
Closing as we've agreed we won't fix this.
