### ISSUE TITLE
Date handling

### ISSUE THREAD

**Issue by lewispb** [DEFRA/ruby-services-team#13]
The system has different ways of handling dates and some 're-invention' of the ruby standard library 'wheel'. 

We should unify and share the logic of converting to and from the various date and time formats needed.

**Comment by lewispb** [comment]
1. Key Person date of birth
2. Registration expires_on
3. RegistrationOrder `#within_ir_renewal_window?`

**Comment by Cruikshanks** [comment]
It is our intention to migrate the remaining functionality in the frontend into our new apps.

Hence have moved this across in the spirit of having a single list of issues, but it is not our intention to fix it because of this.

**Comment by irisfaraway** [comment]
Closing as we've agreed we won't fix this.
