### ISSUE TITLE
Hakiri security vulnerabilties

### ISSUE THREAD

**Issue by lewispb** [DEFRA/ruby-services-team#14]
I have setup Hakiri (https://github.com/hakirisec/hakiri_toolbelt) on my local computer to search our gemfile for security vulnerabilities.

`hakiri system:steps`

```
-----> Searching for vulnerabilities...
!      Found 2 vulnerabilities in Ruby 2.0.0.645
```

`hakiri gemfile:scan -g Gemfile.lock`

```
-----> Searching for vulnerabilities...
!      Found 1  in activesupport 4.0.12
!      Found 1  in devise 3.1.2
!      Found 1  in jquery-rails 3.1.2
!      Found 1  in moped 2.0.2
!      Found 5 vulnerabilities in nokogiri 1.6.2.1
!      Found 8 vulnerabilities in rails 4.0.12
!      Found 2 vulnerabilities in rest-client 1.6.8
!      Found 1  in uglifier 2.5.3
```

After ruby and rails upgrade branch:

```
-----> Searching for vulnerabilities...
!      Found 1  in devise 3.4.1
!      Found 5 vulnerabilities in nokogiri 1.6.2.1
!      Found 2 vulnerabilities in rest-client 1.6.9
```

**Comment by lewispb** [comment]
I'm sure we could tweak devise / nokogiri and rest-client gems to resolve those issues post-upgrade

**Comment by Cruikshanks** [comment]
It is our intention to migrate the remaining functionality in the frontend into our new apps.

Hence have moved this across in the spirit of having a single list of issues, but it is not our intention to fix it because of this.

**Comment by irisfaraway** [comment]
Closing as we've agreed we won't fix this.
