### ISSUE TITLE
PostgreSQL version on Travis-CI and PG gem version upgrade

### ISSUE THREAD

**Issue by cintamani** [DEFRA/ruby-services-team#30]
Our builds have started failing on Travis for the WEX project these days due to failed connection with the Postgres server. 
We have noticed that on the broken builds the Postgres version was upgraded to 10+ while the successful builds run Postgres 9.6.6. 

We believe that the reason behind that could have to deal with the version of the PG gem, but this is not certain. 
Currently, we are running version 0.18.4 (2015). 
We should be able to upgrade our version up to 0.21 (2017) only, but that version does not fix the Postgres connection issue in Travis. 
Subsequent versions (1.x.x up) only supports Rails 5 +.

**Comment by Cruikshanks** [comment]
I think this might have sealed the deal. Time to properly look at moving to Rails 5 once we have shipped some features for the team 😁
