### ISSUE TITLE
Stop wasting references in WEX

### ISSUE THREAD

**Issue by Cruikshanks** [DEFRA/ruby-services-team#32]
The reference number for a WEX registration is currently based on the transient_registration's ID.

However a user could start and abandon a new registration as often as they like, which means we are using up reference numbers and leaving gaps in the sequence.

It's not a critical issue, but it's something that could be relatively easily solved, for example by using the ID of the registration instead at the point a transient_registration gets completed.

**Comment by Cruikshanks** [comment]
Details emailed to PM for putting on the backlog

**Comment by Cruikshanks** [comment]
You happy to close this issue off now @cintamani ?

**Comment by cintamani** [comment]
Very happy :D

**Comment by Cruikshanks** [comment]
See https://github.com/DEFRA/waste-exemptions-engine/pull/233
