### ISSUE TITLE
Reduce duplication in form controllers with disabled actions

### ISSUE THREAD

**Issue by irisfaraway** [DEFRA/ruby-services-team#55]
This came out of discussion here: https://github.com/DEFRA/waste-exemptions-engine/pull/241#discussion_r308131294

We have a lot of forms controllers that have disabled actions like this:

```
    # Overwrite create and go_back as you shouldn't be able to submit or go back
    def create; end

    def go_back; end
```

We should see if there is any way to reduce the duplication, potentially by creating a concern (eg `CannotSubmit` or `CannotGoBack`).

**Comment by cintamani** [comment]
This is all fixed now
