### ISSUE TITLE
Refactor form object attribute assignments

### ISSUE THREAD

**Issue by Cruikshanks** [DEFRA/ruby-services-team#72]
> Originated from https://eaflood.atlassian.net/browse/RUBY-309

We have a lot of form objects that look like this:

```ruby
attr_accessor :foo, :bar, :baz

def initialize(registration)
  self.foo = @transient_registration.foo
  self.bar = @transient_registration.bar
  self.baz = @transient_registration.baz
end
```

This seems like a prime candidate for refactoring. Then we could set the variables once as a constant, rather than having the current repetitive situation.

This came out of a code review here: https://github.com/DEFRA/waste-exemptions-engine/pull/139#discussion_r279315668

**Comment by cintamani** [comment]
This has been addressed using delegate
